###
PATCH http://localhost:5000/dataktp/tolak/1

###
PATCH http://localhost:5000/dataktp/terima/3

###
POST http://localhost:5000/dataktp

{
    "nik": "0123126465465466465",
    "nama": "dzarr al ghifari",
    "status": "diterima"
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "M fikri",
    "email": "test@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
