GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Edita Aulia",
    "email": "editaaulia@gmail.com",
    "Passsword": "12345",
    "tlp": "082125783365"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Dzarr",
    "email": "dzarr@gmail.com",
    "Passsword": "123456",
    "tlp": "082135672280"
}

###
DELETE http://localhost:5000/users/2


<!-- request.rest data ktp -->

###
GET http://localhost:5000/dataktp

###
GET http://localhost:5000/dataktp/1

###
POST http://localhost:5000/dataktp
Content-Type: application/json

{
    "nik": 3523160606800003,
    "name": "MAFTUCHIN",
    "tempat": "JAKARTA",
    "tgl_lahir": "06-06-1973",
    "jenis_kelamin": "LAKI-LAKI",
    "gol_darah": "B",
    "alamat": "JL. MASJID ALFALAH 001/002",
    "agama": "ISLAM",
    "status_perkawinan": "KAWIN",
    "pekerjaan": "WIRASWASTA",
    "kewarganegaraan": "WNI",
    "kode_pos": "16417",
    "status": "PENDING"
}

###
PATCH http://localhost:5000/dataktp/1
Content-Type: application/json

{
    "nik": 3529160606800004,
    "name": "RINA",
    "tempat": "JAKARTA",
    "tgl_lahir": "06-06-1999",
    "jenis_kelamin": "PEREMPUAN",
    "gol_darah": "O",
    "alamat": "JL. DIPONOGORO BLOK B/164",
    "agama": "ISLAM",
    "status_perkawinan": "BELUM KAWIN",
    "pekerjaan": "PELAJAR",
    "kewarganegaraan": "WNI",
    "kode_pos": "16418",
    "status": "PENDING"
}

###
DELETE http://localhost:5000/dataktp/2