###
PATCH http://localhost:5000/dataktp/tolak/1

###
PATCH http://localhost:5000/dataktp/terima/3

###
POST http://localhost:5000/dataktp

{
    "nik": "0123126465465466465",
    "nama": "dzarr al ghifari",
    "status": "diterima"
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "edita",
    "email": "editaaulia@gmail.com",
    "password": "edita123",
    "confPassword": "edita123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "editaaulia@gmail.com",
    "password": "edita123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout


###
GET http://localhost:5000/admin

###
GET http://localhost:5000/admin/1

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "name": "edita",
    "email": "test@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}
